<?php
/**
 * Custom capability management for the Astrologer API plugin.
 *
 * Registers plugin-specific capabilities and maps CPT meta caps
 * to the appropriate primitive capabilities based on ownership.
 *
 * @package Astrologer\Api
 */

declare( strict_types = 1 );

namespace Astrologer\Api\Capabilities;

use Astrologer\Api\Support\Contracts\Bootable;
use WP_Role;
use WP_User;

/**
 * Manages custom capabilities and role assignments.
 *
 * Capabilities registered:
 * - astrologer_manage_settings
 * - astrologer_calculate_chart
 * - astrologer_save_chart
 * - astrologer_view_any_chart
 * - astrologer_run_cli
 *
 * Plus all CPT primitive capabilities generated by
 * capability_type ['astrologer_chart', 'astrologer_charts'].
 */
final class CapabilityManager implements Bootable {

	/**
	 * Plugin-specific custom capabilities (not CPT-generated).
	 *
	 * @var list<string>
	 */
	private const PLUGIN_CAPABILITIES = array(
		'astrologer_manage_settings',
		'astrologer_calculate_chart',
		'astrologer_save_chart',
		'astrologer_view_any_chart',
		'astrologer_run_cli',
	);

	/**
	 * CPT primitive capabilities generated by WordPress for
	 * capability_type ['astrologer_chart', 'astrologer_charts'].
	 *
	 * @var list<string>
	 */
	private const CPT_CAPABILITIES = array(
		'edit_astrologer_charts',
		'edit_others_astrologer_charts',
		'edit_private_astrologer_charts',
		'edit_published_astrologer_charts',
		'publish_astrologer_charts',
		'read_private_astrologer_charts',
		'delete_astrologer_charts',
		'delete_others_astrologer_charts',
		'delete_private_astrologer_charts',
		'delete_published_astrologer_charts',
		'edit_astrologer_chart',
		'delete_astrologer_chart',
		'read_astrologer_chart',
	);

	/**
	 * Default capability-to-role mapping.
	 *
	 * Each key is a capability string, value is the list of WP roles
	 * that should receive that capability.
	 *
	 * @var array<string, list<string>>
	 */
	private const DEFAULT_MAP = array(
		'astrologer_manage_settings'         => array( 'administrator' ),
		'astrologer_calculate_chart'         => array( 'administrator', 'editor', 'author', 'contributor', 'subscriber' ),
		'astrologer_save_chart'              => array( 'administrator', 'editor', 'author', 'subscriber' ),
		'astrologer_view_any_chart'          => array( 'administrator' ),
		'astrologer_run_cli'                 => array( 'administrator' ),
		'edit_astrologer_charts'             => array( 'administrator', 'editor', 'author', 'subscriber' ),
		'edit_others_astrologer_charts'      => array( 'administrator' ),
		'edit_private_astrologer_charts'     => array( 'administrator', 'editor' ),
		'edit_published_astrologer_charts'   => array( 'administrator', 'editor', 'author', 'subscriber' ),
		'publish_astrologer_charts'          => array( 'administrator', 'editor', 'author', 'subscriber' ),
		'read_private_astrologer_charts'     => array( 'administrator', 'editor' ),
		'delete_astrologer_charts'           => array( 'administrator', 'editor', 'author', 'subscriber' ),
		'delete_others_astrologer_charts'    => array( 'administrator' ),
		'delete_private_astrologer_charts'   => array( 'administrator', 'editor' ),
		'delete_published_astrologer_charts' => array( 'administrator', 'editor', 'author', 'subscriber' ),
		'edit_astrologer_chart'              => array( 'administrator', 'editor', 'author', 'subscriber' ),
		'delete_astrologer_chart'            => array( 'administrator', 'editor', 'author', 'subscriber' ),
		'read_astrologer_chart'              => array( 'administrator', 'editor', 'author', 'subscriber' ),
	);

	/**
	 * Register WordPress hooks.
	 */
	public function boot(): void {
		add_filter( 'user_has_cap', array( $this, 'filter_user_has_cap' ), 10, 4 );
		add_filter( 'map_meta_cap', array( $this, 'filter_map_meta_cap' ), 10, 4 );
	}

	/**
	 * Add custom capabilities to all roles during activation.
	 *
	 * Called by Activator (F1.11). Safe to call multiple times.
	 */
	public function add_capabilities(): void {
		$map = $this->get_capability_map();

		foreach ( $map as $cap => $role_names ) {
			foreach ( $role_names as $role_name ) {
				$role = get_role( $role_name );

				if ( $role instanceof WP_Role && ! $role->has_cap( $cap ) ) {
					$role->add_cap( $cap );
				}
			}
		}
	}

	/**
	 * Remove all custom capabilities from all roles during uninstall.
	 *
	 * Called by Uninstaller (F1.11).
	 */
	public function remove_capabilities(): void {
		$all_caps  = array_merge( self::PLUGIN_CAPABILITIES, self::CPT_CAPABILITIES );
		$all_roles = wp_roles()->roles;

		foreach ( array_keys( $all_roles ) as $role_name ) {
			$role = get_role( $role_name );

			if ( $role instanceof WP_Role ) {
				foreach ( $all_caps as $cap ) {
					$role->remove_cap( $cap );
				}
			}
		}
	}

	/**
	 * Get the full capability-to-role map, filtered.
	 *
	 * @return array<string, list<string>>
	 */
	public function get_capability_map(): array {
		/**
		 * Filter the capability-to-role mapping.
		 *
		 * @param array<string, list<string>> $map Capability map where keys are capability names
		 *                                          and values are arrays of role slugs.
		 */
		return apply_filters( 'astrologer_api/capability_map', self::DEFAULT_MAP );
	}

	/**
	 * Get the list of all custom capabilities (plugin + CPT).
	 *
	 * @return list<string>
	 */
	public function get_all_capabilities(): array {
		return array_merge( self::PLUGIN_CAPABILITIES, self::CPT_CAPABILITIES );
	}

	/**
	 * Get the list of plugin-specific (non-CPT) capabilities.
	 *
	 * @return list<string>
	 */
	public function get_plugin_capabilities(): array {
		return self::PLUGIN_CAPABILITIES;
	}

	/**
	 * Dynamically grant capabilities based on the role map.
	 *
	 * WordPress passes the user's current capabilities as an associative array
	 * where each key is a capability name and value is boolean true.
	 * We check whether the user's roles qualify for each custom capability.
	 *
	 * @param array<string, bool>   $allcaps All capability names the user has.
	 * @param array<string, bool>   $caps    Requested capability names.
	 * @param array<string, mixed>  $args    Arguments passed to current_user_can().
	 * @param WP_User               $user    The user object.
	 * @return array<string, bool> Modified capabilities.
	 */
	public function filter_user_has_cap( array $allcaps, array $caps, array $args, WP_User $user ): array {
		$map        = $this->get_capability_map();
		$user_roles = (array) $user->roles;

		foreach ( $map as $cap => $required_roles ) {
			// phpcs:ignore WordPress.PHP.StrictInArray.MissingTrueStrict -- loose comparison is fine for role name matching.
			if ( count( array_intersect( $user_roles, $required_roles ) ) > 0 ) {
				$allcaps[ $cap ] = true;
			}
		}

		return $allcaps;
	}

	/**
	 * Map meta capabilities for the astrologer_chart CPT.
	 *
	 * Resolves ownership-based caps so that users can only edit/delete
	 * their own charts unless they have the "others" capability.
	 *
	 * @param list<string> $caps    Required primitive capabilities.
	 * @param string       $cap     Meta capability being checked.
	 * @param int          $user_id User ID.
	 * @param array<mixed> $args    Additional arguments (typically the post ID).
	 * @return list<string> Required primitive capabilities.
	 */
	public function filter_map_meta_cap( array $caps, string $cap, int $user_id, array $args ): array {
		// Only handle our CPT meta caps.
		$meta_caps = array(
			'edit_astrologer_chart',
			'delete_astrologer_chart',
			'read_astrologer_chart',
		);

		if ( ! in_array( $cap, $meta_caps, true ) ) {
			return $caps;
		}

		// If no post ID provided, let WordPress handle it.
		if ( ! isset( $args[0] ) || ! is_numeric( $args[0] ) ) {
			return $caps;
		}

		$post = get_post( (int) $args[0] );

		if ( ! $post instanceof \WP_Post || 'astrologer_chart' !== $post->post_type ) {
			return $caps;
		}

		$post_type_obj = get_post_type_object( $post->post_type );

		if ( ! $post_type_obj instanceof \WP_Post_Type ) {
			return $caps;
		}

		$is_owner = (int) $post->post_author === $user_id;

		// Determine the required primitive caps based on the meta cap and ownership.
		return match ( $cap ) {
			'read_astrologer_chart'   => $this->map_read_cap( $post, $post_type_obj, $user_id ),
			'edit_astrologer_chart'   => $this->map_edit_cap( $post, $is_owner ),
			'delete_astrologer_chart' => $this->map_delete_cap( $post, $is_owner ),
		};
	}

	/**
	 * Map the read meta capability for a chart.
	 *
	 * @param \WP_Post      $post    The chart post.
	 * @param \WP_Post_Type $pto     The post type object.
	 * @param int           $user_id The user ID.
	 * @return list<string> Required primitive capabilities.
	 */
	private function map_read_cap( \WP_Post $post, \WP_Post_Type $pto, int $user_id ): array {
		if ( (int) $post->post_author === $user_id ) {
			return array( 'read' );
		}

		if ( 'publish' === $post->post_status && $pto->public ) {
			return array( 'read' );
		}

		return array( 'read_private_astrologer_charts' );
	}

	/**
	 * Map the edit meta capability for a chart.
	 *
	 * @param \WP_Post $post     The chart post.
	 * @param bool     $is_owner Whether the user owns the chart.
	 * @return list<string> Required primitive capabilities.
	 */
	private function map_edit_cap( \WP_Post $post, bool $is_owner ): array {
		if ( $is_owner ) {
			if ( 'publish' === $post->post_status ) {
				return array( 'edit_published_astrologer_charts' );
			}

			if ( 'private' === $post->post_status ) {
				return array( 'edit_private_astrologer_charts' );
			}

			return array( 'edit_astrologer_charts' );
		}

		$caps_required = array( 'edit_others_astrologer_charts' );

		if ( 'publish' === $post->post_status ) {
			$caps_required[] = 'edit_published_astrologer_charts';
		} elseif ( 'private' === $post->post_status ) {
			$caps_required[] = 'edit_private_astrologer_charts';
		} else {
			$caps_required[] = 'edit_astrologer_charts';
		}

		return $caps_required;
	}

	/**
	 * Map the delete meta capability for a chart.
	 *
	 * @param \WP_Post $post     The chart post.
	 * @param bool     $is_owner Whether the user owns the chart.
	 * @return list<string> Required primitive capabilities.
	 */
	private function map_delete_cap( \WP_Post $post, bool $is_owner ): array {
		if ( $is_owner ) {
			if ( 'publish' === $post->post_status ) {
				return array( 'delete_published_astrologer_charts' );
			}

			if ( 'private' === $post->post_status ) {
				return array( 'delete_private_astrologer_charts' );
			}

			return array( 'delete_astrologer_charts' );
		}

		$caps_required = array( 'delete_others_astrologer_charts' );

		if ( 'publish' === $post->post_status ) {
			$caps_required[] = 'delete_published_astrologer_charts';
		} elseif ( 'private' === $post->post_status ) {
			$caps_required[] = 'delete_private_astrologer_charts';
		} else {
			$caps_required[] = 'delete_astrologer_charts';
		}

		return $caps_required;
	}
}
