/**
 * Entry point of the React application for WordPress.
 *
 * This file:
 * 1. Finds all containers with data-astrologer-component
 * 2. Reads the component type and props
 * 3. Mounts the appropriate React component
 *
 * The containers are generated by shortcodes and Gutenberg blocks.
 */

import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { ComponentMounter } from './ComponentMounter';
import './index.css';

/**
 * Initializes all Astrologer components on the page.
 * Runs when the DOM is ready.
 */
function initAstrologerComponents(): void {
    // Find all containers with components to mount
    const containers = document.querySelectorAll<HTMLElement>(
        '[data-astrologer-component]',
    );

    if (containers.length === 0) {
        return;
    }

    containers.forEach((container) => {
        const componentType = container.dataset.astrologerComponent;
        const propsJson = container.dataset.props || '{}';

        if (!componentType) {
            return;
        }

        try {
            const props = JSON.parse(propsJson);

            // Create the React root and mount the component
            const root = createRoot(container);
            root.render(
                <StrictMode>
                    <ComponentMounter type={componentType} props={props} />
                </StrictMode>,
            );
        } catch (error) {
            // Silently fail in production
            void error;
        }
    });
}

// Initialize when the DOM is ready
if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', initAstrologerComponents);
} else {
    // DOM already loaded
    initAstrologerComponents();
}
