<?php
/**
 * Frontend assets manager for Astrologer API.
 *
 * @package Astrologer_API_Playground
 * @since   1.0.0
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * Class responsible for managing frontend (React) assets.
 *
 * It is responsible for:
 * - Loading the compiled React bundle
 * - Loading CSS styles (Tailwind)
 * - Passing configuration and data to the frontend via wp_localize_script
 *
 * @since 1.0.0
 */
class Astrologer_API_Frontend {

    /**
     * Flag to prevent enqueuing assets multiple times.
     *
     * @var bool
     */
    private static bool $assets_enqueued = false;

    /**
     * Constructor - registers hooks.
     */
    public function __construct() {
        // Register assets on the frontend (do not enqueue automatically)
        add_action( 'wp_enqueue_scripts', array( $this, 'register_assets' ) );
    }

    /**
     * Registers assets without enqueuing them.
     * Assets will be enqueued only when needed (shortcode/block).
     *
     * @return void
     */
    public function register_assets(): void {
        $dist_path = ASTROLOGER_API_PLUGIN_DIR . 'frontend/dist/';
        $dist_url  = ASTROLOGER_API_PLUGIN_URL . 'frontend/dist/';

        // Check if the production bundle exists.
        // If it does NOT exist and WP_DEBUG is enabled, use dev mode (Vite).
        if ( ! file_exists( $dist_path . 'assets/main.js' ) ) {
            if ( defined( 'WP_DEBUG' ) && WP_DEBUG ) {
                $this->register_dev_assets();
            }
            return;
        }

        // Register CSS (generated by Vite)
        // Vite may generate either "main.css" or "index.css" depending on config.
        $css_handle = 'astrologer-api-frontend';
        if ( file_exists( $dist_path . 'assets/main.css' ) ) {
            wp_register_style(
                $css_handle,
                $dist_url . 'assets/main.css',
                array(),
                ASTROLOGER_API_VERSION
            );
        } elseif ( file_exists( $dist_path . 'assets/index.css' ) ) {
            wp_register_style(
                $css_handle,
                $dist_url . 'assets/index.css',
                array(),
                ASTROLOGER_API_VERSION
            );
        }

        // Register JavaScript bundle
        wp_register_script(
            'astrologer-api-frontend',
            $dist_url . 'assets/main.js',
            array( 'wp-element' ),
            ASTROLOGER_API_VERSION,
            true // In footer
        );

        // Add type="module" for ES modules
        add_filter( 'script_loader_tag', array( $this, 'add_module_type' ), 10, 3 );

        // Pass configuration to the frontend
        wp_localize_script( 'astrologer-api-frontend', 'astrologerApiConfig', self::get_frontend_config() );
    }

    /**
     * Registers assets for development with Vite HMR.
     *
     * During development, Vite serves files directly with hot reload.
     * This method loads the HMR client and the main entry point.
     *
     * @return void
     */
    private function register_dev_assets(): void {
        // Vite dev server URL (default: http://[::1]:5173)
        $vite_server = 'http://[::1]:5173';

        // Register Vite client for HMR (loaded by the browser)
        wp_register_script(
            'vite-client',
            $vite_server . '/@vite/client',
            array(),
            null,
            false
        );

        // Register the main entry point
        wp_register_script(
            'astrologer-api-frontend',
            $vite_server . '/src/main.tsx',
            array( 'vite-client', 'wp-element' ),
            null,
            true
        );

        // Add type="module"
        add_filter( 'script_loader_tag', array( $this, 'add_module_type' ), 10, 3 );

        // Pass configuration
        wp_localize_script( 'astrologer-api-frontend', 'astrologerApiConfig', self::get_frontend_config() );
    }

    /**
     * Enqueues frontend assets when necessary.
     *
     * Called by shortcodes and blocks to ensure CSS and JS
     * are loaded on the page.
     *
     * @return void
     */
    public static function enqueue_frontend_assets(): void {
        // Avoid loading multiple times
        if ( self::$assets_enqueued ) {
            return;
        }

        // Register assets if they are not already registered
        if ( ! wp_script_is( 'astrologer-api-frontend', 'registered' ) ) {
            ( new self() )->register_assets();
        }

        // Enqueue CSS
        if ( wp_style_is( 'astrologer-api-frontend', 'registered' ) ) {
            wp_enqueue_style( 'astrologer-api-frontend' );
        }

        // Enqueue JavaScript
        if ( wp_script_is( 'astrologer-api-frontend', 'registered' ) ) {
            wp_enqueue_script( 'astrologer-api-frontend' );
        }

        self::$assets_enqueued = true;
    }

    /**
     * Adds type="module" to script tags for ES modules.
     *
     * @param string $tag    Original HTML tag.
     * @param string $handle Script handle.
     * @param string $src    Script URL.
     * @return string Modified HTML tag.
     */
    public function add_module_type( string $tag, string $handle, string $src ): string {
        $module_handles = array(
            'astrologer-api-frontend',
            'vite-client',
        );

        if ( in_array( $handle, $module_handles, true ) ) {
            $tag = str_replace( '<script ', '<script type="module" ', $tag );
        }

        return $tag;
    }

    /**
     * Returns the configuration to pass to the frontend.
     *
     * Includes:
     * - REST endpoints URLs
     * - Nonce for authentication
     * - Visual settings configured in the admin
     *
     * @return array
     */
    public static function get_frontend_config(): array {
        $settings = Astrologer_API_Settings::get_settings();

        return array(
            // Base URL for the plugin REST API calls
            'restUrl'   => rest_url( 'astrologer/v1/' ),

            // Nonce for AJAX/REST security (if the user is logged in)
            'nonce'     => wp_create_nonce( 'wp_rest' ),

            // Visual settings configured in the admin
            'settings'  => array(
                'language'    => $settings['language'],
                'houseSystem' => $settings['house_system'],
                'theme'       => $settings['theme'],
                'sidereal'    => $settings['sidereal'],
                'uiThemeMode' => $settings['ui_theme_mode'],
                'collapseBirthFormOnSubmit' => (bool) $settings['collapse_birth_form_on_submit'],
                'formOutputMode' => $settings['form_output_mode'] ?? 'inline',
            ),

            // Translations for the frontend
            'i18n' => array(
                'loading'       => __( 'Loading...', 'astrologer-api' ),
                'error'         => __( 'Error while loading', 'astrologer-api' ),
                'submit'        => __( 'Calculate', 'astrologer-api' ),
                'name'          => __( 'Name', 'astrologer-api' ),
                'birthDate'     => __( 'Birth date', 'astrologer-api' ),
                'birthTime'     => __( 'Birth time', 'astrologer-api' ),
                'birthPlace'    => __( 'Birth place', 'astrologer-api' ),
                'natalChart'    => __( 'Natal Chart', 'astrologer-api' ),
                'aspects'       => __( 'Aspects', 'astrologer-api' ),
                'elements'      => __( 'Elements', 'astrologer-api' ),
                'modalities'    => __( 'Modalities', 'astrologer-api' ),
                'fire'          => __( 'Fire', 'astrologer-api' ),
                'earth'         => __( 'Earth', 'astrologer-api' ),
                'air'           => __( 'Air', 'astrologer-api' ),
                'water'         => __( 'Water', 'astrologer-api' ),
                'cardinal'      => __( 'Cardinal', 'astrologer-api' ),
                'fixed'         => __( 'Fixed', 'astrologer-api' ),
                'mutable'       => __( 'Mutable', 'astrologer-api' ),

                // Form field labels (SubjectFormFields)
                'labelName'             => __( 'Name', 'astrologer-api' ),
                'labelDay'              => __( 'Day', 'astrologer-api' ),
                'labelMonth'            => __( 'Month', 'astrologer-api' ),
                'labelYear'             => __( 'Year', 'astrologer-api' ),
                'labelHour'             => __( 'Hour', 'astrologer-api' ),
                'labelMinutes'          => __( 'Minutes', 'astrologer-api' ),
                'labelCity'             => __( 'City', 'astrologer-api' ),
                'labelCountryCode'      => __( 'Country (code)', 'astrologer-api' ),
                'placeholderCountryCode' => __( 'IT, US, UK...', 'astrologer-api' ),
                'labelLatitude'         => __( 'Lat', 'astrologer-api' ),
                'labelLongitude'        => __( 'Lng', 'astrologer-api' ),
                'labelTimezone'         => __( 'Time zone', 'astrologer-api' ),
                'placeholderTimezone'   => __( 'Europe/Rome', 'astrologer-api' ),

                // Shared form strings
                'calculating'           => __( 'Calculating...', 'astrologer-api' ),
                'errorCalculating'      => __( 'Error while calculating', 'astrologer-api' ),
                'errorTitle'            => __( 'Error', 'astrologer-api' ),
                'chartTitle'            => __( 'Chart', 'astrologer-api' ),
                'firstSubject'          => __( 'First subject', 'astrologer-api' ),
                'secondSubject'         => __( 'Second subject', 'astrologer-api' ),
                'dataLoadedFor'         => __( 'Data loaded for', 'astrologer-api' ),
                'birthDataHeading'      => __( 'Birth Data', 'astrologer-api' ),

                // BirthForm
                'birthData'             => __( 'Birth Data', 'astrologer-api' ),
                'showForm'              => __( 'Show form', 'astrologer-api' ),
                'hideForm'              => __( 'Hide form', 'astrologer-api' ),

                // SynastryForm
                'synastryTitle'         => __( 'Synastry', 'astrologer-api' ),
                'synastrySubmit'        => __( 'Calculate synastry', 'astrologer-api' ),

                // TransitForm
                'transitTitle'          => __( 'Transits on natal chart', 'astrologer-api' ),
                'transitSubmit'         => __( 'Calculate transits', 'astrologer-api' ),
                'natalChartHeading'     => __( 'Natal chart', 'astrologer-api' ),
                'transitHeading'        => __( 'Transit', 'astrologer-api' ),
                'includeHouseComparison' => __( 'Include houses comparison', 'astrologer-api' ),

                // CompositeForm
                'compositeTitle'        => __( 'Composite Chart', 'astrologer-api' ),
                'compositeSubmit'       => __( 'Calculate Composite Chart', 'astrologer-api' ),
                'compositeSuccess'      => __( 'Composite chart calculated successfully.', 'astrologer-api' ),

                // SolarReturnForm
                'solarReturnTitle'      => __( 'Solar Return Chart', 'astrologer-api' ),
                'solarReturnSubmit'     => __( 'Calculate Solar Return', 'astrologer-api' ),
                'returnYearHeading'     => __( 'Return Year', 'astrologer-api' ),

                // LunarReturnForm
                'lunarReturnTitle'      => __( 'Lunar Return Chart', 'astrologer-api' ),
                'lunarReturnSubmit'     => __( 'Calculate Lunar Return', 'astrologer-api' ),
                'returnPeriodHeading'   => __( 'Return Period', 'astrologer-api' ),

                // CompatibilityForm
                'compatibilityTitle'    => __( 'Compatibility score', 'astrologer-api' ),
                'compatibilitySubmit'   => __( 'Calculate compatibility', 'astrologer-api' ),
                'resultTitle'           => __( 'Result', 'astrologer-api' ),
                'scoreLabel'            => __( 'Score:', 'astrologer-api' ),
                'destinyLabel'          => __( 'Destiny:', 'astrologer-api' ),
                'yes'                   => __( 'Yes', 'astrologer-api' ),
                'no'                    => __( 'No', 'astrologer-api' ),

                // NowForm
                'nowTitle'              => __( 'Current moment chart', 'astrologer-api' ),
                'nowSubmit'             => __( 'Calculate current chart', 'astrologer-api' ),
                'nowSubjectName'        => __( 'Subject name', 'astrologer-api' ),
                'nowPlaceholder'        => __( 'Now', 'astrologer-api' ),
                'nowSuccess'            => __( 'Chart calculated successfully.', 'astrologer-api' ),

                // MoonPhaseDisplay
                'moonPhase'             => __( 'Moon Phase', 'astrologer-api' ),
                'moonPhaseNoData'       => __( 'Enter birth data to view the moon phase.', 'astrologer-api' ),
                'sunMoonAngle'          => __( 'Sun-Moon angle', 'astrologer-api' ),
                'moonPhase_new_moon'    => __( 'New Moon', 'astrologer-api' ),
                'moonPhase_waxing_crescent' => __( 'Waxing Crescent', 'astrologer-api' ),
                'moonPhase_first_quarter'   => __( 'First Quarter', 'astrologer-api' ),
                'moonPhase_waxing_gibbous'  => __( 'Waxing Gibbous', 'astrologer-api' ),
                'moonPhase_full_moon'       => __( 'Full Moon', 'astrologer-api' ),
                'moonPhase_waning_gibbous'  => __( 'Waning Gibbous', 'astrologer-api' ),
                'moonPhase_last_quarter'    => __( 'Last Quarter', 'astrologer-api' ),
                'moonPhase_waning_crescent' => __( 'Waning Crescent', 'astrologer-api' ),
            ),
        );
    }
}
